# Praxis Agent Configuration
# Edit this file to customize your agent settings

# Primary AI Provider Configuration
primary_llm:
  provider: openrouter  # Options: openrouter, openai, anthropic, ollama
  model: deepseek/deepseek-r1-0528:free
  api_key: "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"  # Add your API key here
  base_url: https://openrouter.ai/api/v1
  max_tokens: 4096
  temperature: 0.7
  timeout: 60

# Fallback AI Provider (used when primary fails)
fallback_llm:
  provider: ollama
  model: llama2:7b
  api_key: null
  base_url: http://localhost:11434
  max_tokens: 4096
  temperature: 0.7
  timeout: 60

# Embedding model for memory and search
embedding_model: sentence-transformers/all-MiniLM-L6-v2

# System Configuration
system:
  log_level: INFO  # Options: DEBUG, INFO, WARNING, ERROR
  max_log_files: 10
  log_rotation_mb: 10
  enable_system_tray: true
  auto_start: true
  max_concurrent_tasks: 3
  sandbox_enabled: true

# Security and Safety Settings
security:
  allow_file_operations: true
  allow_network_access: true
  allow_code_execution: true
  restricted_paths:
    - C:\Windows\System32
    - C:\Program Files
    - C:\Users\*\AppData\Roaming\Microsoft
  max_file_size_mb: 100

# File and Directory Paths
data_dir: ./data
logs_dir: ./logs
memory_db_path: ./data/memory.db
vector_db_path: ./data/vector_store

# Memory System Configuration
max_short_term_memories: 100
max_long_term_memories: 10000
memory_retention_days: 30
